### ISSUE TITLE
[documentation]: Wrong example

### ISSUE THREAD

**Issue by arthurXpro** [kiwilan/php-xml-reader#12]
### What happened?

![Screenshot_20241128_160228](https://github.com/user-attachments/assets/5ce5a6d5-10ca-4249-b405-054a98e36a99)
please change it to  use Kiwilan\XmlReader\XmlReader;

I spent an hour searching for the error :d 

### How to reproduce the bug

read the documentation:
https://github.com/kiwilan/php-xml-reader

thank you in advance!

### Package Version

1.1.0

### PHP Version

8.3

### Which operating systems does with happen with?

Linux

**Comment by ewilan-riviere** [comment]
Sorry about that, it's fixed now!
